# Key Bind                          Action                              Description

# Mouse Buttons
MBTN_LEFT                           cycle pause                         # don't do anything
MBTN_BACK                           playlist-prev                       # skip to the previous file
MBTN_FORWARD                        playlist-next                       # skip to the next file

# Mouse Wheel
WHEEL_UP                           add volume 2                         # add volume +2
WHEEL_DOWN                         add volume -2                        # add volume -2

# Keyboard Arrows
RIGHT                               seek  5                             # seek 5 seconds forward
LEFT                                seek -5                             # seek 5 seconds backward
UP                                  add volume 5                        # add volume +5
DOWN                                add volume -5                       # add volume -5
Shift+RIGHT                         seek  80                            # seek 80 seconds forward

# Files Navigation
[                                   add chapter -1                      # skip to the previous chapter
]                                   add chapter 1                       # skip to the next chapter

>                                   playlist-next                       # skip to the next file
<                                   playlist-prev                       # skip to the previous file

# Subtitles
z                                   add sub-delay -0.5                  # shift subtitles 500 ms earlier
x                                   add sub-delay +0.5                  # delay subtitles by 500 ms

s                                   cycle sub                           # switch to the next subtitle
S                                   cycle sub down                      # switch to the previous subtitle

# Audio
a                                   cycle audio                         # switch to the next audio track
A                                   cycle audio down                    # switch to the previous audio track