osc=no                                      # Hide default on-screen controller
osd-bar=no                                  # Disable OSD bar
sub-file-paths=Subs                         # Set the path for subtitle files
sub-auto=all                                # Automatically load all subtitles
fs=yes                                      # Start in fullscreen mode
sub-font=Cairo                              # Set the subtitle font to Cairo
volume=130                                  # Set the default volume to 130%
volume-max=200                              # Set the maximum volume to 200%
cursor-autohide=100                         # Hide the cursor after 0.1 seconds of inactivity
alang=jpn,ja,Japanese,eng,en,English        # Audio language priority
slang=ar,ara,Arabic,eng,en,English          # Subtitle language priority