osc=no                                      # Hide default on-screen controller
osd-bar=no                                  # Disable OSD bar
sub-file-paths=Subtitles                    # Set the path for subtitle files
sub-auto=all                                # Automatically load all subtitles
fs=yes                                      # Start in fullscreen mode
sub-font=IBM Plex Sans Arabic               # Set the subtitle font to Cairo
volume=100                                  # Set the default volume to 100%
volume-max=200                              # Set the maximum volume to 200%
cursor-autohide=100                         # Hide the cursor after 0.1 seconds of inactivity
alang=jpn,ja,Japanese,eng,en,English        # Audio language priority
slang=ar,ara,Arabic,eng,en,English          # Subtitle language priority
save-position-on-quit=no                    # Disable saving position on quit
